# products = [
#     {"rice": {"name": "RICE", "Category": "Food", "Quantity": 348}},
#     {"sunglasses": {"name": "SUNGLASSES", "Category": "Fashion", "Quantity": 324}},
#     {"milkshake": {"name": "MILKSHAKE", "Category": "Drinks", "Quantity": 431}},
#     {"scarf": {"name": "SCARF", "Category": "Clothing","Quantity": 312}},
#     {"cakes": {"name": "CAKES", "Category": "Food", "Quantity": 234}},
#     {"beans": {"name": "BEANS", "Category": "Food", "Quantity": 343}},
#     {"coffee": {"name": "COFFEE", "Category": "Drinks", "Quantity": 312}},
#     {"sportshoes": {"name": "SPORTSHOES", "Category":"Sportswear","Quantity": 214}},
#     {"soda": {"name": "SODA", "Category": "Drinks", "Quantity": 341}},
#     {"shirt": {"name": "SHIRT", "Category":"Clothing", "Quantity": 112}},
# ]



products = [
    {"name":"rice", "Category":"Food", "Quantity":348},
    {"name":"sunglasses", "Category":"Fashion", "Quantity":324},
    {"name":"milkshake", "Category":"Drinks", "Quantity":431},
    {"name":"scarf", "Category":"Clothing", "Quantity":312},
    {"name":"cakes", "Category":"Food", "Quantity":234},
    {"name":"beans", "Category":"Food", "Quantity":343},
    {"name":"coffee", "Category":"Drinks", "Quantity":312},
    {"name":"sportshoes", "Category":"Sportswear", "Quantity":214},
    {"name":"soda", "Category":"Drinks", "Quantity":341},
    {"name":"shirt", "Category":"Clothing", "Quantity":112},
    {"name":"socks", "Category":"Clothing", "Quantity":112},
    {"name":"shoes", "Category":"Clothing", "Quantity":112},
    {"name":"t-shirt", "Category":"Clothing", "Quantity":112},
    {"name":"trousers", "Category":"Clothing", "Quantity":112},
    {"name":"glasses", "Category":"Fashion", "Quantity":112},
    {"name":"watch", "Category":"Fashion", "Quantity":112},
    {"name":"bag", "Category":"Fashion", "Quantity":112},
    {"name":"shorts", "Category":"Clothing", "Quantity":112},
    {"name":"jacket", "Category":"Clothing", "Quantity":112},
    {"name":"jeans", "Category":"Clothing", "Quantity":112},
    {"name":"towel", "Category":"Clothing", "Quantity":112},
    {"name":"sandals", "Category":"Clothing", "Quantity":112},
    {"name":"t-shirt", "Category":"Clothing", "Quantity":112},
    {"name":"trousers", "Category":"Clothing", "Quantity":112},
    {"name":"glasses", "Category":"Fashion", "Quantity":112},
    {"name":"watch", "Category":"Fashion", "Quantity":112},
    {"name":"bag", "Category":"Fashion", "Quantity":112},
    {"name":"shorts", "Category":"Clothing", "Quantity":112},
    {"name":"jacket", "Category":"Clothing", "Quantity":112},
]